### PR TITLE
Switch reconfiguration groovy script to use configs stored on disk

### LINKED ISSUE #89: indigo reconfigure is failing
http://54.183.26.131:8080/view/Manage/job/Irel_reconfigure-jobs/

It's been for two weeks now. I think it's a problem with an improperly escaped character. Or else it's something like the script is getting too big or otherwise unloadable.

The last successful build was on the 14th: changes around that time https://github.com/ros/rosdistro/commits/master/indigo/distribution.yaml?page=3

Searches suggesting a bad character or content in the generated script
https://stackoverflow.com/questions/14630404/java-lang-classformaterror-invalid-constant-pool-index-63
https://stackoverflow.com/questions/12333849/classformaterror-unknown-constant-tag-in-class-xy

Exception below. 

```
01:55:16.611 Writing groovy script '/tmp/reconfigure_jobs/reconfigure_jobs.groovy' to reconfigure 10914 jobs
01:55:18.821 + echo # END SECTION
01:55:18.821 # END SECTION
01:55:41.514 FATAL: Invalid this class index 41987 in constant pool in class file Script1
01:55:41.514 java.lang.ClassFormatError: Invalid this class index 41987 in constant pool in class file Script1
01:55:41.514 	at java.lang.ClassLoader.defineClass1(Native Method)
01:55:41.514 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
01:55:41.514 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
01:55:41.514 	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:55)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.createClass(GroovyClassLoader.java:515)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.onClassNode(GroovyClassLoader.java:532)
01:55:41.514 	at groovy.lang.GroovyClassLoader$ClassCollector.call(GroovyClassLoader.java:536)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit$14.call(CompilationUnit.java:779)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:970)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:548)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:526)
01:55:41.514 	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:503)
01:55:41.514 	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:302)
01:55:41.514 	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:281)
01:55:41.514 	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:731)
01:55:41.514 	at groovy.lang.GroovyShell.parse(GroovyShell.java:743)
01:55:41.514 	at groovy.lang.GroovyShell.parse(GroovyShell.java:698)
01:55:41.514 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:648)
01:55:41.514 	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:636)
01:55:41.514 	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:93)
01:55:41.514 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
01:55:41.514 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:764)
01:55:41.514 	at hudson.model.Build$BuildExecution.build(Build.java:205)
01:55:41.514 	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
01:55:41.514 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
01:55:41.514 	at hudson.model.Run.execute(Run.java:1744)
01:55:41.514 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
01:55:41.514 	at hudson.model.ResourceController.execute(ResourceController.java:98)
01:55:41.514 	at hudson.model.Executor.run(Executor.java:374)
```

### PR DESCRIPTION
**Pull request by tfoote**
instead of embedding the config inside the body of the script.

The groovy execution context was running out of memory. The script was over 200Mb.

Fixes #89

### CODE REVIEW

**Comment by tfoote** [comment]
Successfully run using the branch: http://54.183.26.131:8080/job/Irel_reconfigure-jobs/256/console

File: ros_buildfarm/templates/snippet/reconfigure_jobs.groovy.em [hunk 1]
```diff
@@ -102,14 +84,27 @@ def format_xml(doc) {
...
+config_dir = build.getWorkspace().toString() + '/reconfigure_jobs/configs'
+
+def jobs = []
+def dir = new File(config_dir)
+dir.eachFileRecurse (FileType.FILES) { file ->
+    jobs << file
+}
+
+if (jobs.size() != @(expected_num_jobs)) {
+    println "WARNING: Found different number of job configs than expected!! " + jobs.size() + " is not @(expected_num_jobs) as expected."
```
Comment (dirk-thomas) [inline ros_buildfarm/templates/snippet/reconfigure_jobs.groovy.em]: Should this really only be a warning? I would think if this happens failing the job and sending a notification email would be more appropriate.

**Comment by tfoote** [comment]
updated to error if the diff count is off. It ran successfully the last night: http://54.183.26.131:8080/view/Manage/job/Irel_reconfigure-jobs/265/
